version: '3.3'
services:
  mysql:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8mb4 --max_connections=1024 --collation-server=utf8mb4_unicode_ci --sql_mode="NO_ENGINE_SUBSTITUTION" --explicit_defaults_for_timestamp="ON"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: hebanghui
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rundata

